### ISSUE TITLE
nix-shell -A develop not working

### ISSUE THREAD

**Issue by vlaci** [nix-community/setup.nix#22] opened 2019-10-26 14:19 UTC
The following works fine on NixOS 19.03 but fails on 19.09
```
$ git clone https://github.com/nix-community/setup.nix
$ cd setup.nix/examples/package
$ git rev-parse HEAD
509af1daa29eb2a45cc00152d2569067b48b7710
$ nix-shell setup.nix -A develop
building '/nix/store/44ix0svk5p20vdb5pycz5yf1njbr2xsl-setup.json.drv'...
error: attribute 'shellHook' missing, at /nix/store/9kaq240kqk2nynqnzd0x7fzwwhddbyj2-source/default.nix:286:17
(use '--show-trace' to show detailed location information)
```

Apparently `buildPythonPackage` no longer adds a `shellHook` to the derivation

**Comment by datakurre** [comment] 2019-10-26 15:59
Thanks for the report. Should be fixable.

**Comment by vlaci** [comment] 2019-10-26 20:38
I think it broke in https://github.com/NixOS/nixpkgs/commit/f7e28bf5d8181926e600a222cb70180519d09726
Now there are format specific hooks such as `pipShellHookand` and`setuptoolsShellHook`

**Comment by datakurre** [comment] 2019-10-26 21:05
That it is and I could fix it once I am on keyboard again. I don’t usually upgrade nixpkgs in my projects unless I need to, so I don’t always see these in time. So, thanks again!

Breakages like these are the price in building on top of the internals on nixpkgs Python, but this has been working so well lately for our projects that I don’t want to give up yet :)

**Comment by vlaci** [comment] 2019-10-26 21:19
Absolutely :+1: 
I have a `nixos-old` channel set-up which I use for projects where having bleeding-edge versions is not critical. That's how I can still use and enjoy this awesome tool too :)
<details>
<summary>For further reference if someone would need details...</summary>

1. Set-up channel
```
$ sudo nix-channel --add https://nixos.org/channels/nixos-19.03 nixos-old
$ sudo nix-channel --update nixos-old
```
2. change the first line in `setup.nix`
```diff
-{ pkgs ? import <nixpkgs> {}
+{ pkgs ? import <nixos-old> {}
```
3. profit
</details>

**Comment by datakurre** [comment] 2019-10-27 12:08
@vlaci Would you have a good idea on how to detect if shellHooks should be setuptoolsShellHook in the used nixpkgs revision?

Or possibly I just change to setuptoolsShellHook and bump up major version.

Oh, and outside on this issue, I'm open for idea for making setup.nix better. My own plan is to eventually merged this into pip2nix scaffolding.

**Comment by vlaci** [comment] 2019-10-27 12:31
Maybe something like:
```nix
if old ? shellHook then
  shellHook = old.shellHook + shellHook
else if old ? setuptoolsShellHook then
  shellHook = old.setuptoolsShellHook + shellHook
else
  abort "Unsupported"
```
Eventually IMHO a major version bump should be done to remove this complexity

It would be interesting to support e.g `pyproject.toml` based packages too. If supporting additional package formats is a goal then I am unsure that exposing `{format}ShellHook` attributes on the API would be a good idea. I suppose this should be an implementation detail as it seams to be the case in nixpkgs.

**Comment by datakurre** [comment] 2019-10-27 13:23
Does `pyproject` already work with `buildPythonPackage`?

But back to the issue, I probably found the root cause.  I was not properly overriding the resulting Python derivation breaking its shell support in recent 19.09. According to nixpkgs docs, I should use `postShellHook` instead.

https://github.com/nix-community/setup.nix/commit/dd09828515f5c06417eee47b688342ab81aaecda

**Closed** 2019-10-27 13:36 UTC

**Comment by datakurre** [comment] 2019-10-27 13:47
Thanks. I tagged v3.3.0 and checked that both nixpkgs 19.03 and 19.09 channels should work with that.

**Comment by vlaci** [comment] 2019-10-27 16:27
> Does `pyproject` already work with `buildPythonPackage`?
> 
> But back to the issue, I probably found the root cause. I was not properly overriding the resulting Python derivation breaking its shell support in recent 19.09. According to nixpkgs docs, I should use `postShellHook` instead.
> 
> [dd09828](https://github.com/nix-community/setup.nix/commit/dd09828515f5c06417eee47b688342ab81aaecda)

Yes, `pyproject.toml` is supported.
